apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: jx
  labels:
    app: nexus
    chart: nexus-0.1.41
    gitops.jenkins-x.io/pipeline: namespaces
    heritage: Helm
    release: nexus
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: csi-obs 
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: jx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      imagePullSecrets:
      - name: huawei-key
      containers:
      - name: nexus
        image: swr.ap-southeast-3.myhuaweicloud.com/loansaas/saas/nexus3:3.30.0
        ports:
        -  containerPort: 8081
        -  containerPort: 8082
        -  containerPort: 8083
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-data
      volumes:
        - name: nexus-data-volume
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: jx
spec:
  selector:
    app: nexus
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8081
    - name: docker
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: maven
      protocol: TCP
      port: 8083
      targetPort: 8083