# Source: jxboot-helmfile-resources/templates/repositories.yaml
apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  name: "mydev"
  labels:
    jenkins.io/gitSync: "false"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
spec:
  description: "the git repository for the Mydev environment"
  provider: "https://github.com"
  providerKind: 'github'
  providerName: 'github'
  org: "q1323829945"
  repo: "jenkinX2"
  httpCloneURL: "https://github.com/q1323829945/jenkinX2.git"
  url: "https://github.com/q1323829945/jenkinX2.git"
  scheduler:
    kind: Scheduler
    name: "in-repo"
