# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "mydev"
    team: mydev
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: "mydev"
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/q1323829945/jenkinX2.git
  kind: Permanent
  label: Mydev
  order: 500
  promotionStrategy: "Auto"
  namespace: "mydev"
