apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: https://nexus-jx.saas-ops.finline.app
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: saas-ops.finline.app
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: lizheng2@sunline.cn
      enabled: true
      production: false
      secretName: jx-privkey
  repository: nexus
  secretStorage: local
  vault: {}
  webhook: lighthouse
