apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: nexus-docker.saas-ops.finline.app
  environments:
  - key: mydev
    namespace: mydev
    owner: q1323829945
    promotionStrategy: Auto
    repository: jenkinX2
  - key: dev
    owner: q1323829945
    repository: jenkinX2
  - key: staging
    namespace: my-staging
    owner: q1323829945
    remoteCluster: true
    repository: production
  - key: production
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    domain: saas-ops.finline.app
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: lizheng2@sunline.cn
      enabled: true
      production: false
      secretName: jx-privkey
  pipelineUser:
    username: q1323829945
  repository: nexus
  secretStorage: local
  vault: {}
  webhook: lighthouse
