apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: nexus-docker.saas-ops.finline.app
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    domain: saas-ops.finline.app
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: lizheng2@sunline.cn
      enabled: true
      production: false
      secretName: jx-privkey
  repository: nexus
  secretStorage: local
  vault: {}
  webhook: lighthouse
