apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        q1323829945/h5-test: true
        q1323829945/h52: true
        q1323829945/jenkinX2: true
        q1323829945/production: true
        q1323829945/test2: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        q1323829945/h5-test: merge
        q1323829945/h52: merge
        q1323829945/jenkinX2: merge
        q1323829945/production: merge
        q1323829945/test2: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - q1323829945/jenkinX2
        - q1323829945/production
        - q1323829945/h5-test
        - q1323829945/h52
        - q1323829945/test2
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - q1323829945/jenkinX2
        - q1323829945/production
        - q1323829945/h5-test
        - q1323829945/h52
        - q1323829945/test2
      target_url: http://lighthouse-jx.saas-ops.finline.app/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
