filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: chartmuseum
  url: https://artifacthub.io/packages/helm/choerodon/chartmuseum
releases:
- chart: stable\chartmuseum
  version: 2.14.2
  name: chartmuseum
  values:
  - ../../versionStream/charts/stable/chartmuseum/values.yaml.gotmpl
templates: {}
renderedvalues: {}
